version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_APP: wsgi.py
      FLASK_ENV: development
      SECRET_KEY: 7a197fe73206411f84ca66fc